import React from "react";
import "./about.less";
export default function About() {
  return (
    <div className="about" id="About">
      <div
        className="about_inner animate animate__animated"
        data-animate="animate__fadeInIn"
        data-animation-delay="2 .1s"
      >
        <h2
        // className="animate animate__animated"
        // data-animate="animate__fadeInUp"
        // data-animation-delay="2 .1s"
        >
          About <i> Coinversation</i>
        </h2>
        <p className="text">
          Coinversation Protocol is the first DEFI2.0 protocol platform of
          Polkadot Ecology. It has been expanded from a synthetic asset protocol
          to a derivative ecosystem including parachains, DEX, synthetic asset,
          and stablecoin protocols.
        </p>
        <ul className="first">
          <li>
            <img src={require("../img/1.svg")} alt="logo" />
            <h3>Mint Center</h3>
            <p>
              The CUSD generated by the whole system users mortgaging certain
              collateral. The collateral includes interest-bearing tokens such
              as CTO and DOT, and users can choose the proportion of CUSD they
              need to exchange. If stable currency is used as collateral,
              because it is an interestbearing product, its leverage ratio will
              continue to decrease and it will never be liquidated.{" "}
            </p>
          </li>
          <li>
            <img src={require("../img/2.svg")} alt="logo" />
            <h3>Oracle</h3>
            <p>
              Since the price of mortgage forging needs to be integrated from
              outside network, the oracle is the most important. The initial
              system will use off-chain oracle such as our partner Chainlink,
              DIA to ensure the stability of our forging and liquidation. We
              will work with multiple oracle to ensure users' assets.Cross-chain
              Interest When users put interest-bearing tokens such as CTO and
              DOT into our platform, the platform will show what chain they put
              into, what products they put into, and what the comprehensive rate
              of return is.
            </p>
          </li>
        </ul>
        <ul className="seconed">
          <li>
            <img src={require("../img/3.svg")} alt="logo" />
            <h3>Liquidity Mining</h3>
            <p>
              We will award $CTO to:
              <br /> • Users who form 3USD LP with BUSD USDC USDT on
              Coinversation.
              <br /> • Users who form CUSD+3USD LP
              <br /> • CUSD-CTOLP users
              <br /> • Users who stake $CTO
            </p>
          </li>
          <li>
            <img src={require("../img/4.svg")} alt="logo" />
            <h3>Platform Revenue</h3>
            <p>
              When users put in interest-bearing tokens and generate interest
              automatically. We will charge a certain percentage of the fee for
              the interest-bearing part, which we will vote on the chain to
              determine our percentage. This income will give dividends to $CTO
              collateralized users, and later we will bind with nodes and
              distribute rewards to users who vote for nodes. The fee for stable
              currency exchange will also enter the platform revenue.
            </p>
          </li>
          <li>
            <img src={require("../img/5.svg")} alt="logo" />
            <h3>Liquidation</h3>
            <p>
              The liquidator on the chain can become our liquidation robot. He
              will receive 5% of the total amount of liquidation as a reward.
              Anyone can participate in our liquidator. If bad debts occur, we
              will repay the entire mortgage system from the platform revenue.{" "}
            </p>
          </li>
        </ul>
      </div>
    </div>
  );
}
